### ISSUE TITLE
User Story #3 - News

### ISSUE THREAD

**Issue by AlexKrumins** [Jonorlowski1/Project-1#4]
## User Story
As a music fan, I want to be able to search a preferred artist, so I can know more about similar bands, their catalog, and any recent news headlines.

## Checklist
- [x] Use newsapi to find news about the band
- [x] Use spotify to find more discography information
- [x] Use spotify or songkick to find similar bands

**Comment by Jonorlowski1** [comment]
newsapi might be a bust, we could come back to it later.
